ln -sf config/.bashrc ~
ln -sf config/.gitconfig ~
ln -sf config/.gitignore ~
ln -sf config/.inputrc ~
ln -sf config/.ideavimrc ~
ln -sf config/.pythonrc.py ~
ln -sf config/.tmux.conf ~
ln -sf config/.zshrc ~
ln -sf ../../config/gavrie.zsh-theme ~/.oh-my-zsh/themes
